### ISSUE TITLE
Combine AxisArrays with cat?

### ISSUE THREAD

**Issue by flo12345678** [JuliaArrays/AxisArrays.jl#64]
`a=AxisArray(rand(3,3,3,10),:x,:y,:z,:time);`
`b=AxisArray(rand(3,3,3,20),:x,:y,:z,:time);`
`c=cat(4,a,b)` does not work, am I missing something? Is there something like `c=cat(Axis{:time},a,b)`?

`c=cat(4,a.data,b.data)` works

**Comment by GordStephen** [comment]
I think this should work, if it doesn't then it's a bug. Does `merge(a,b)` do what you want?

**Comment by flo12345678** [comment]
`julia> a=AxisArray(rand(3,3,3,10),:x,:y,:z,:time);

julia> b=AxisArray(rand(3,3,3,20),:x,:y,:z,:time);

julia> c=cat(4,a,b)
ERROR: BoundsError: attempt to access (...
`

**Comment by flo12345678** [comment]
`d=merge(a,b)
ERROR: MethodError: no method matching mergevalues(::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::Symbol)
`

**Comment by flo12345678** [comment]
Is it a Bug or what do I need to do differently?

**Comment by GordStephen** [comment]
My guess is that it's a bug due to the axis values being a range - right now I think the tests (problematically) only check on vectors. What happens if you give full axis definitions with vectors? (`Axis{:x}(collect(1:3))`)

**Comment by flo12345678** [comment]
`a=AxisArray(rand(3,3,3,10),Axis{:x}(collect(1:3)),Axis{:y}(collect(1:3)),Axis{:z}(collect(1:3)),Axis{:time}(collect(1:10)));

julia> b=AxisArray(rand(3,3,3,20),Axis{:x}(collect(1:3)),Axis{:y}(collect(1:3)),Axis{:z}(collect(1:3)),Axis{:time}(collect(1:20)));

julia> c=cat(4,a,b)
ERROR: BoundsError: attempt to access (
`

**Comment by flo12345678** [comment]
```
merge(a,b)
4-dimensional AxisArray{Float64,4,...} with axes:
    :x, [1,2,3]
    :y, [1,2,3]
    :z, [1,2,3]
    :time, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
And data, a 3×3×3×20 `Array{Float64,4}:
```
merge works but I'm expecting 3x3x3x30 ...?

**Comment by GordStephen** [comment]
In the case of `merge` it's a feature, not a bug, it overwrites the values in `a` because both `a` and `b` have `:time` values from 1:10. The behavior you want (naive concat) should be supported by `cat`, but clearly isn't working. I'll look into that.

**Comment by flo12345678** [comment]
Thx!

**Comment by GordStephen** [comment]
As of right now the `gs-fixcat` branch will allow `cat(4, a, b)` as described above. That being said, I'm not sure that use case should actually be supported... it's unclear what concatenating an axis indexed 1:10 with an axis indexed 1:20 means (see the discussion in #25). Currently the behaviour is to create a new axis with values [1:10; 1:20] which is clearly a bad idea and only works because the `checkaxis` function is broken (if it were working the concatenation in question would throw an invalid axis error).

I think the idiomatic AxisArrays approach to this would be to explicitly give your time points meaningful axis values (1:10 and 11:30, for example). Then `cat` will result in a valid axis or better yet `merge` will accomplish what you want automagically.

In the bigger picture it may be worth considering whether AxisArrays need a `cat` method at all... The only reason we have one is because I implemented it before realising that what I really needed were the `merge` and `join` methods (which accomplish the same tasks but use the axis name/value information to "do the right thing" automatically).

**Comment by GordStephen** [comment]
To summarize the various issues here: the original behaviour should fail, but was failing for the wrong reasons. After https://github.com/JuliaArrays/AxisArrays.jl/commit/c82427f3c2907e19551e8b93e7fcabd4b40d3487 it now succeeds, which is also a bug (due to #68). Once both of these issues are resolved it should fail with an `ArgumentError` thrown by `checkaxis` (instead of a `BoundsError`).

**Comment by flo12345678** [comment]
Ok Thx, I will use merge and join then.
